# Generated by Django 5.0.5 on 2024-05-09 06:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="author",
            field=models.ManyToManyField(to="books.author", verbose_name="Authors"),
        ),
    ]
