# Generated by Django 5.0.5 on 2024-05-09 06:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0002_alter_book_author"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booksubcategory",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="books.bookcategory",
                verbose_name="Book Category",
            ),
        ),
    ]
