# Generated by Django 5.0.5 on 2024-05-15 06:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0003_alter_booksubcategory_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="books.bookcategory",
                verbose_name="Book Category",
            ),
        ),
    ]
