# Generated by Django 5.0.5 on 2024-05-10 08:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0002_useraddress_user_address"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="address",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="user.useraddress",
                verbose_name="User Address",
            ),
        ),
    ]
